name: bigboxx-kernel
base: core18
version: git
summary: Kernel module of IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. This module, named Kernel, has the role to collect
  sensor data and persist it.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  mongo:
    command: env LC_ALL=C mongod --bind_ip 0.0.0.0 --port=27017 --pidfilepath $SNAP_USER_DATA/mongod.pid --journal --dbpath $SNAP_USER_DATA/mongo
    daemon: simple
    restart-condition: never

  redis:
    command: env LC_ALL=C redis-server
    daemon: simple
    restart-condition: never
    after: [mongo]

  node:
    command: env SNAP_COMMON=$SNAP_COMMON SNAP_DATA=$SNAP_DATA node $SNAP/server.js
    daemon: simple
    restart-condition: never
    after: [redis]

hooks:
  install:
    plugs: [home, network, network-bind]
  configure:
    plugs: [home, network, network-bind]

slots:
  tokens:
    content: tokens
    interface: content
    read:
      - $SNAP_DATA

plugs:
  home:
  network:
  network-bind:

parts:
  kernel:
    source: .
    plugin: nodejs
    nodejs-version: 16.20.1
    stage-packages:
      - mongodb-server
      - mongodb-clients 
      - mongodb-server-core
      - redis-server
